version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: eisenhower-matrix
    container_name: eisenhower-matrix_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - net_eisenhower-matrix

  db:
    image: mysql:8.0.31
    container_name: eisenhower-matrix_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: pwr
      MYSQL_PASSWORD: pw
      MYSQL_USER: usr
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "33060:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - net_eisenhower-matrix

  nginx:
    image: nginx:alpine
    container_name: eisenhower-matrix_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - net_eisenhower-matrix

networks:
  net_eisenhower-matrix:
    driver: bridge
